mono/gtk-sharp

- gtk/ListStore.custom
This patch introduces changes to `Gtk.ListStore.AppendValues` so it reduces the number of calls to value setting.
Particularly, this was 3 times as slower on inserting values than `InsertWithValues` in a ListStore with 860 rows and 9 columns.
Given the documentation at [0], it seems that the latter would trigger `row_changed` and `rows_reordered` many more times than intended, at least once for each column on each row. With this patch, it would be triggered just once for each row.
[0] - https://developer.gnome.org/gtk3/stable/GtkListStore.html#gtk-list-store-insert-with-values
> Optimize ListStore.AppendValues

- generator/CodeGenerator.cs
Return 64 for command line usage errors (following the error codes in sysexits.h).
> Fix exit codes in code generator

- gdk/glue/windowmanager.c
This is a PR for the gtk-sharp-2-12-branch
This fixes XamBug #176, which results from incompatible pointer sizes on different CPU architectures.
> gdk: Use platform independent ptr type in gdk_net_client_list

- atk/atk-api.raw
- parser/gapi_pp.pl
- sources/Makefile.am
- sources/sources.xml
This is more of a check to see if the project is alive at the point of discussing changes.
- For some reason I had to revert that patch since after cloning I get some crlf changes that I cannot remove unless I make a commit.
- Then basically there are a few patches to update atk to the version 2.14.0 which is the version in centos 7.2
My idea would be to update all the packages so we target gtk 3.14. Then release and make a branch out of it.
Then it would be a matter of updating the project to the last gtk stable which currently is 3.20 and release again and branch.
And finally target gtk master.
Ideas on this? A review on the patches would be great as well, and getting them merged even better.
> Update atk to version 2.14.0

- sample/gtk-gio/MountOperation.cs
Using `mono 4.4.0.40`:
```
`MountOperation.cs(56,50): error CS0104: `EventArgs' is an ambiguous reference between`System.EventArgs' and `GLib.EventArgs'
```
> Fix ambiguous references

- pango/Pango.metadata
- pango/pango-api.raw
- sources/Makefile.am
- sources/sources.xml
Another patch for the series I am making to get the bindings up to date
> Update pango API to version 1.36.8

- gtk/Builder.custom
[The GtkBuilder class _is_ already part of the GTK+ 2.12 API] [0]. Only 2
functions were added in 2.14 which we do not generate or use. The GtkBuilder
class is already shipped in GTK#2 but the custom code was disabled, which
provides a reflection based auto binder. I have tested the auto binder and it
works perfectly. [The same code is used in the GTK#3 branch] [1] btw.
[0]: https://developer.gnome.org/gtk2/stable/GtkBuilder.html#gtk-builder-new
[1]: https://github.com/mono/gtk-sharp/blob/master/gtk/Builder.cs
> enable custom code of GtkBuilder for auto binding support

- glib/Object.cs
- glib/ToggleRef.cs
- gtk/Object.custom
Sinking is done when object is attached to parent... Sinking everything
when Raw is set results into incrementing ref count for no reason, hence
memory leak...
g_object_ref and g_object_unref is just so random code that is not even
worth explaining why it's deleted
> Fixed memory leaks caused by sinking everything

- generator/ByRefGen.cs
- generator/ManagedCallString.cs
- generator/Parameters.cs
This avoid an extra heap allocation for each object passed by ref so it can be transitioned directly into native memory. Native counterparts will handle data mutation, so managed will see it anyway.
https://gist.github.com/Therzok/f0627b87a5f89c1e3e5b2aab58b59b08
Don't merge yet, as I need to test it.
> Generator: ByRef generator now passes the value by ref

- README
Link for getting started with Gtk went to outdated generic mono documentation.
> Updated Mono Hand Book link from outdated docs

- glib/ListBase.cs
This makes it so we use the optimized iteration version, coupled with doing the check on what free function to use only once.
> [GLib] Optimize freeing a native list from managed

- generator/MarshalGen.cs
- generator/SymbolTable.cs
This fixes a few leaks caused by gstrdup-ing by firing and forgetting.
https://gist.github.com/Therzok/822d377e69476d172f434aa79ef74aed
> [Gen] Always free strdup strings as they're not held by native

- glib/GType.cs
- glib/IntPtrEqualityComparer.cs
- glib/Makefile.am
- glib/Object.cs
- glib/glib.csproj
This improves performance on all key operations on the dictionaries by preventing the boxing of the IntPtr.
> [GLib] Use a custom eq comparer for IntPtr dictionary keys.

- Makefile.am
As per the former contents of that file, makefile.win32 is dead.
Having it in EXTRA_DIST when it no longer exists prevents "make
dist" from running.
> Don't try to include "makefile.win32" in EXTRA_DIST

- gtk/Gtk.metadata
```
public void Popup(Gtk.Widget parent_menu_shell, Gtk.Widget parent_menu_item, Gtk.MenuPositionFunc func, uint button, uint activate_time) {
GtkSharp.MenuPositionFuncWrapper func_wrapper = new GtkSharp.MenuPositionFuncWrapper (func);
func_wrapper.PersistUntilCalled (); // This line is added which frees the wrapper after call
gtk_menu_popup(Handle, parent_menu_shell == null ? IntPtr.Zero : parent_menu_shell.Handle, parent_menu_item == null ? IntPtr.Zero : parent_menu_item.Handle, func_wrapper.NativeDelegate, IntPtr.Zero, button, activate_time);
}
```
> Fix Gtk.Menu leak

- gdk/Gdk.metadata
CairoHelper.Create would pass "owner=false" to the ctor of Cairo.Context, which would then wrongfully increment its reference counter. Thus making it impossible to free the context or any resource it is holding with Dispose().
This adds the metadata attribute to correctly generate CairoHelper.Create with "owner=true".
Test: Make a new Gtk#3.0 app and add this to the constructor of your window.
```
Maximize ();
Drawn += (o, args) => Gdk.CairoHelper.Create ((o as Window).Window).Dispose ();
System.Threading.Tasks.Task.Run (() => { 
while (true) { 
System.Threading.Thread.Sleep (100);
Gtk.Application.Invoke ((sender, e) => QueueDraw ());
}
});
```
> Fix cairo context memory leak

- gtk/ColorSelection.custom
If compiling gtk-sharp using mono 4.8.0 on debian 8 I get error like:
generated/ColorSelection.custom(47,20): error CS0233: `Gdk.Color' does not have a predefined size, therefore sizeof can only be used in an unsafe context (consider using System.Runtime.InteropServices.Marshal.SizeOf)
> Correct use of sizeof method in gtk/ColorSelection.custom

- glib/Value.cs
This is a mirror of a patch in a glib newer than the one we distribute with Mono.
> [GLib] Value should not unset if type isn't set.

- glib/Marshaller.cs
- glib/Signal.cs
- glib/ToggleRef.cs
This commit changes the stack to use glib conversions between utf16 and utf8, only doing one iteration of the string on conversion.
This patch doesn't handle error checking yet, this is a TODO
> [GLib] Optimize string marshalling

- glib/Object.cs
Based on msdn docs https://msdn.microsoft.com/en-us/library/b05d59ty(v=vs.110).aspx, it should be null for non-indexed properties. Thus, we can safely use the variant which doesn't pass an index.
> [GLib] Make GetPropertyCallback not send an index.

- gdk/Display.custom
- gdk/Event.cs
- gdk/EventButton.cs
- gdk/EventClient.cs
- gdk/EventConfigure.cs
- gdk/EventCrossing.cs
- gdk/EventDND.cs
- gdk/EventExpose.cs
- gdk/EventFocus.cs
- gdk/EventGrabBroken.cs
- gdk/EventHelper.custom
- gdk/EventKey.cs
- gdk/EventMotion.cs
- gdk/EventOwnerChange.cs
- gdk/EventProperty.cs
- gdk/EventProximity.cs
- gdk/EventScroll.cs
- gdk/EventSelection.cs
- gdk/EventSetting.cs
- gdk/EventVisibility.cs
- gdk/EventWindowState.cs
- gdk/Gdk.metadata
- gdk/Makefile.am
- gtk/Application.cs
- gtk/Global.custom
This was freeing the event right after construction. Manually bind these as symbols.xml doesn't support smart owned binding.
> [Gdk,Gtk] Fix possible invalid memory access with GdkEvent.

- glib/Source.cs
Before, the code would check whether the source was registered in the dictionary. Thus, it would return true without invoking the source removal.
> [GLib] Backwards compatibility with source removal

- glib/DestroyNotify.cs
- glib/Idle.cs
- glib/Timeout.cs
- gtk/Application.cs
Mirrors behaviour from TimeoutProxy. Split into two classes, the Invoke without args class is now smaller. Fast-path by not creating extra junk along the way. Performance is now comparable to GLib.Timeout.Add.
> [Gtk] Make Application.Invoke snappier.

- atk/Atk.metadata
Atk defines the properties via const strings, not literal strings, so the perl parser grabs the wrong id. https://github.com/GNOME/atk/blob/125dac528339267821dbbd6da9b19fe9949334e9/atk/atkobject.c#L259-L273
> [Atk] Fix property names.

- bootstrap-generic
Current Debian packaging puts libtool in its own package (libtool-bin)
leaving only libtoolize in the main package. The mono build process
uses libtoolize not libtool, so during autogen check for libtoolize
not libtool.
> Check for libtoolize rather than libtool

- glib/ValueArray.cs
The "ref" operation of GValueArray is a copy, so we don't have a
choice.
I can reproduce the crash with GStreamer, but the code code to do it is:
```c-sharp
GLib.ValueArray va = new GLib.ValueArray (1);
GLib.Value v = new GLib.Value (va);
GLib.ValueArray va2 = (GLib.ValueArray) v;
```
> ValueArray: Create copy when receiving pointer

- sample/test/TestRange.cs
Recent addition of C#8 features to mcs possibly broke this:
```
mcs -out:WidgetViewer.exe -r:../../glib/glib-sharp.dll -r:../../pango/pango-sharp.dll -r:../../atk/atk-sharp.dll -r:../../gdk/gdk-sharp.dll -r:../../gtk/gtk-sharp.dll ./TestCheckButton.cs ./TestColorSelection.cs ./TestRadioButton.cs ./TestRange.cs ./TestStatusbar.cs ./TestDialog.cs ./TestFlipping.cs ./TestSizeGroup.cs ./TestCombo.cs ./TestComboBox.cs ./WidgetViewer.cs
./TestCombo.cs(17,14): warning CS0612: `Gtk.Combo' is obsolete
./TestRange.cs(35,6): error CS0104: `Range' is an ambiguous reference between `System.Range' and `Gtk.Range'
@/external/bockbuild/stage/lib/mono/4.5/mscorlib.dll (Location of the symbol related to previous error)
@/external/bockbuild/builds/gtk-sharp-None/sample/test/../../gtk/gtk-sharp.dll (Location …
```
> Fix build failure with mcs caused by C#8 changes in mcs

- Makefile.include
- audit/makefile
- configure.in.in
- sample/GtkDemo/Makefile.am
- sample/Makefile.am
mcs sets the timestamp in the PE header to 0 which breaks some MS internal tools, let's use csc instead.
> Use csc instead of mcs
